---
- meta: noop
  vars: &default_remove_key_params
    url: "{{github_api_url}}/{{github_deploy_key_id}}"
    method: DELETE
    status_code: 204

- name: Remove key with username
  uri:
    <<: *default_remove_key_params
    user: "{{github_username}}"
    password: "{{github_password}}"
    force_basic_auth: yes
  when: github_username is defined

- name: Remove key with API token
  uri:
    <<: *default_remove_key_params
    headers:
      Authorization: token {{github_access_token}}
  when: github_username is undefined and github_access_token is defined
